org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Duser.language=en
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
minecraft_version=1.20.1
forge_version=47.1.0
mod_id=animania
mod_name=Animania Reborn
mod_license=LGPL-3.0-only
mod_version=0.1.1
mod_group_id=com.animania
jade_version=11.13.1+forge
jei_version=15.20.0.106
emi_version=1.1.22+1.20.1+forge
