"""Translate the original per-model animation methods, without pooling breed equations.

Geometry/setupAngles is already baked by convert-legacy-models.mjs. Sleeping poses
are handled separately by LegacyAnimalModel and GeneratedLegacySleep.
This generator writes only its generated Java output; it does not run tests.
"""
from pathlib import Path
import json
import re

root = Path('.upstream-animania/src/main/java/com/animania/addons')
models = Path('src/main/resources/assets/animania/legacy_models')
target = Path('src/main/java/com/animania/client/GeneratedLegacyMotion.java')

def body(source, start):
    a = source.index('{', start)
    b, depth = a + 1, 1
    while depth:
        depth += (source[b] == '{') - (source[b] == '}')
        b += 1
    return source[a + 1:b - 1]

def translate(code):
    code = re.sub(r'super\.\w+\([^;]*\);', '', code)
    code = re.sub(r'ModelPose sleepingPose\s*=[^;]*;', '', code)
    code = re.sub(r'sleepingPose\.\w+\([^;]*\);', '', code)
    code = re.sub(r'(?:this\.)?setupAngles\(\);', '', code)
    code = re.sub(r'this\.ball\.rotation\s*=[^;]*;', '', code) # HamsterBallLayer owns ball rendering.
    code = re.sub(r'this\.\w+\.postRender\([^;]*\);', '', code) # Legacy GL-only helper, not a model pose.
    code = re.sub(r'(\w+)\s+instanceof\s+(Entity\w+)', r'\1.isType("\2")', code)
    # Entity class names in strings must remain intact for subtype dispatch.
    code = re.sub(r'(?<!["\w])Entity\w*\b(?!")', 'LegacyMotionContext', code)
    code = code.replace('MathHelper.', 'Mth.').replace('AnimaniaConfig.gameRules.showParts', 'com.animania.common.config.LegacyConfig.SHOW_PARTS.get()')
    code = code.replace('.world.getWorldTime()', '.worldTime()')
    code = code.replace('.rotationPitch', '.pitch').replace('.ticksExisted', '.ticks')
    for old, new in [('rotateAngleX','xRot'),('rotateAngleY','yRot'),('rotateAngleZ','zRot'),
                     ('rotationPointX','x'),('rotationPointY','y'),('rotationPointZ','z'),
                     ('setRotationPoint','setPos'),('showModel','visible')]:
        code = code.replace('.' + old, '.' + new)
    return code

entries = []
for file in sorted(root.rglob('Model*.java')):
    key = file.relative_to(root).with_suffix('').as_posix().lower()
    datafile = models / (key + '.json')
    if not datafile.exists():
        continue
    source = re.sub(r'/\*[\s\S]*?\*/|//[^\n]*', '', file.read_text(encoding='utf-8'))
    methods = {}
    for match in re.finditer(r'public\s+void\s+(setLivingAnimations|setRotationAngles)\s*\(([^)]*)\)', source):
        methods[match[1]] = (translate(match[2]), translate(body(source, match.end())))
    if not methods:
        continue
    nodes = json.loads(datafile.read_text(encoding='utf-8'))['nodes']
    arrays = re.findall(r'ModelRenderer\s+(\w+)\[\]', source)
    arrays += re.findall(r'ModelRenderer\[\]\s+(\w+)', source)
    fields = [n['name'] for n in nodes]
    entries.append((key, methods, fields, arrays))

out = ['''package com.animania.client;

import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.util.Mth;
import java.util.Map;

/** Generated by tools/convert-legacy-motion.py from Animania's LGPL-3.0 1.12 models.
 * Each model retains its own animation formulas. */
final class GeneratedLegacyMotion {
    interface Motion {
        void apply(LegacyMotionContext context, float swing, float amount, float age, float yaw, float pitch, float partial);
    }
    static Motion create(String key, Map<String, ModelPart> parts) {
        return switch (key) {''']
for i, (key, _, _, _) in enumerate(entries):
    out.append(f'            case "{key}" -> new Motion{i}(parts);')
out += ['            default -> null;', '        };', '    }']
for i, (key, methods, fields, arrays) in enumerate(entries):
    out += [f'    // {key}', f'    private static final class Motion{i} implements Motion {{', '        private float headRotationAngleX; private float lastLimb;']
    out.append('        private final ModelPart ' + ', '.join(fields) + ';')
    for array in arrays:
        if array not in fields: out.append(f'        private final ModelPart[] {array};')
    out.append(f'        Motion{i}(Map<String, ModelPart> parts) {{')
    for field in fields: out.append(f'            {field} = parts.get("{field}");')
    for array in arrays:
        members = [f for f in fields if re.fullmatch(re.escape(array) + r'\d+', f)]
        if members: out.append(f'            {array} = new ModelPart[] {{' + ', '.join(members) + '};')
    out += ['        }', '        @Override public void apply(LegacyMotionContext context, float swing, float amount, float age, float yaw, float pitch, float partial) {',
            '            headRotationAngleX = pitch * Mth.DEG_TO_RAD;']
    if 'setLivingAnimations' in methods: out.append('            setLivingAnimations(context, swing, amount, partial);')
    if 'setRotationAngles' in methods: out.append('            setRotationAngles(swing, amount, age, yaw, pitch, 0.0625F, context);')
    out.append('        }')
    for name, (args, code) in methods.items():
        out.append(f'        private void {name}({args}) {{\n{code}\n        }}')
    out.append('    }')
out.append('}')
target.write_text('\n'.join(out) + '\n', encoding='utf-8')
print(f'Translated {len(entries)} original model animation implementations to {target}')
